name: Update README with Weekly Journal Entries

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "developer-journal/*.md"
      - "!developer-journal/README.md"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Run update script
        run: node .github/scripts/update-readme.js

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add developer-journal/README.md
          git commit -m "Update README with new weekly journal entries" || echo "No changes to commit."
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/sobert-moe/sobert-moe.git HEAD:main
